# Generated by Django 3.0 on 2019-12-28 11:05

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.get_image_path, verbose_name='Fotograf')),
                ('name', models.TextField(verbose_name='Haberin Adı')),
                ('content', models.TextField(verbose_name='Haberin İçeriği')),
                ('date', models.DateTimeField(max_length=50, verbose_name='Tarih')),
                ('editor', models.CharField(max_length=50, verbose_name='Haberi Yayınlayan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haber',
            },
        ),
    ]
